version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase...
  build:
    commands:
      - echo build started on `date`
      - mvn test
  post_build:
    commands:
      - echo build completed on `date`
      - mvn package
artifacts:
  files:
    - target/messageUtil-1.0.jar
    - appspec.yml
  discard-paths: yes